apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: meme-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: image_frontend:local
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: meme-storage
          mountPath: /data/output
      volumes:
      - name: meme-storage
        persistentVolumeClaim:
          claimName: meme-storage
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: meme-generator
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort
