apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  namespace: meme-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: image_producer:local
        ports:
        - containerPort: 8000
