apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: meme-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: image_worker:local
        volumeMounts:
        - name: meme-storage
          mountPath: /data/output
      volumes:
      - name: meme-storage
        persistentVolumeClaim:
          claimName: meme-storage
